### PR TITLE
SeqScan implemented & HeapFile 1 mtd remaining

### PR DESCRIPTION
**Pull request by NachiketUN**
Implemented all the methods is SeqScan,
But iterator(TransactionId tid) method in HeapFile is yet to be implemented.

### CODE REVIEW

**Comment by sbshah97** [comment]
Description please! And get your teammates to review your code!

**Comment by hlpr98** [comment]
at the end add...
`class HeapFileIterator implements DbFileIterator{
  private Iterator<Tuple> tupIt = null;
  private TransactionId tid = null;
  private HeapFile f = null;
  private int pgNo = 0;

  public HeapFileIterator(TransactionId tid , HeapFile f){
    this.tid = tid;
    this.f = f;
  }

  public void open() throws DbException, TransactionAbortedException{
    pgNo = 0;
    PageId pgId = new HeapPageId(f.getId(), pgNo);
    Page page = Database.getBufferPool().getPage(tid,pgId,Permissions.READ_ONLY);
    HeapPage heapPage = (HeapPage)page;
    tupIt = heapPage.iterator();
  }

    public boolean hasNext()  throws DbException, TransactionAbortedException{
        if(tupIt==null)
            return false;

        if(tupIt.hasNext())
            return true;
        else{
            if(pgNo>=f.numPages()-1)
                return false;
            else{
                PageId pgId = new HeapPageId(f.getId(), pgNo+1);
                Page page = Database.getBufferPool().getPage(tid,pgId,Permissions.READ_ONLY);
                HeapPage heappage = (HeapPage)page;
                return heappage.iterator().hasNext();
            }
        }
    }


    public Tuple next()  throws DbException, TransactionAbortedException, NoSuchElementException{
        if(tupIt==null)
            throw new NoSuchElementException();

        if (tupIt.hasNext())
            return tupIt.next();
        else
        {
            PageId pgId = new HeapPageId(f.getId(), pgNo+1);
            Page page = Database.getBufferPool().getPage(tid,pgId,Permissions.READ_ONLY);
            HeapPage heappage = (HeapPage)page;

            if (page!=null)
                if (heappage.iterator().hasNext())
                {
                    pgNo++;
                    tupIt = heappage.iterator();
                    return tupIt.next();
                }
            throw new NoSuchElementException();

        }


    }


    public void rewind() throws DbException, TransactionAbortedException{
        close();
        open();

    }


    public void close(){
        tupIt = null;
        pgNo = 0;
    }
}
`

**Comment by hlpr98** [comment]
and in the iterator method add..
`return new HeapFileIterator(tid,this);`

**Comment by hlpr98** [comment]
this was the best idea i could come up with.. couldn't incorporate in the same class...
my code is based on the TupleIterator class

**Review by rjshubh — COMMENTED** [review]
in the numpage() method the return type is int . plz check it .

**Review by NachiketUN — COMMENTED** [review]
Yeah the return type is int indeed.

**Pull request merged**
