### PR TITLE
BufferPool,HeapPageId,RecordId and HeapPage (not used)

### PR DESCRIPTION
**Pull request by hlpr98**
I too got the same error as @anumehaagrawal when i tried to run test in the new directory but not in my original directory. pls help out.

### CODE REVIEW

**Comment by hlpr98** [comment]
no problem now .. the error is resolved

**Comment by sbshah97** [comment]
Review this PR amongst yourselves and push!

**Comment by hlpr98** [comment]
In HeapPage.. I`m getting the following test result
screenshot from 2017-06-14 01-10-16

From this test i can see that the `getPageData()` method isn't working properly.. Pls suggest a solution.

**Comment by hlpr98** [comment]
But in HeapPage class when i comment out the 62nd line that is `setBeforeImage()` the following is the test result.
screenshot from 2017-06-14 01-11-14

This shows an error caused due the `iterator()` method. Pls suggest why is it causing the error.

**Comment by sbshah97** [comment]
Check if you're trying to access something that isn't present/defined earlier! That's what Null Pointer Exception usually does!

**Comment by hlpr98** [comment]
Thank you @salman-bhai . Both the errors were resolved. It was caused because the `Tuple` class was not yet implemented which the test was using.

**Comment by sbshah97** [comment]
@hlpr98 Awesome job! Well done.

**Comment by hlpr98** [comment]
#3 
BufferPool completed.
#4 
HeapPageId, HeapPage and RecordId completed

**Comment by anumehaagrawal** [comment]
In HeapPage , on line 320 in the for loop it should be tuplesOnPage instead of just Tuples right?

**Comment by hlpr98** [comment]
nope.. tuplesOnPage is being written now and tuples is already written

**Pull request closed without merging**
